/**
 * @file tkl_flash.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_flash.h"
#include "tuya_error_code.h"
#include "esp_partition.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "freertos/idf_additions.h"
#include "soc/soc.h"

/* TODO: need to consider whether to use locks at the TKL layer*/
#define PARTITION_SIZE         (1 << 12) /* 4KB */
#define FLH_BLOCK_SZ            PARTITION_SIZE

//key
#define SIMPLE_FLASH_KEY_ADDR 0x0 /* offset of tuya data partition */

//KV
#define SIMPLE_FLASH_START (SIMPLE_FLASH_KEY_ADDR + PARTITION_SIZE)
#define SIMPLE_FLASH_SIZE 0x8000 // 32K

//UF
#define UF_PARTITION_NUM     1
#define UF_PARTITION_START  (SIMPLE_FLASH_START + SIMPLE_FLASH_SIZE)
#define UF_PARTITION_SIZE   0x18000 // 96K

#if defined(KV_PROTECTED_ENABLE) && (KV_PROTECTED_ENABLE==1)
#define SIMPLE_FLASH_KV_PROTECTED_START (UF_PARTITION_START + UF_PARTITION_SIZE)
#define SIMPLE_FLASH_KV_PROTECTED_SIZE 0x1000 //4K
#endif

#define GET_TUYA_DATA_PARTITION() esp_partition_find_first(ESP_PARTITION_TYPE_DATA, ESP_PARTITION_SUBTYPE_ANY, "tuya")

typedef struct {
    char *uuid;
    char *authkey;
} tuya_iot_license_t;

/* -------------------------------------------------------------------
 * Flash proxy worker
 *
 * Tasks with PSRAM stacks cannot call esp_partition_read/write/erase:
 * those operations call spi_flash_disable_interrupts_caches_and_other_cpu()
 * which disables the CPU cache, making the PSRAM stack temporarily
 * inaccessible and triggering the assertion in cache_utils.c:167.
 *
 * When __stack_in_psram() detects the caller is on a PSRAM stack, the
 * operation is forwarded via a FreeRTOS queue to a dedicated worker task
 * that has an internal-RAM stack.  The caller blocks on TaskNotify until
 * the worker completes the operation and returns the result.
 * ------------------------------------------------------------------- */
#define FLASH_WORKER_STACK_SIZE  2048
#define FLASH_WORKER_PRIORITY    (configMAX_PRIORITIES - 5)
#define FLASH_QUEUE_DEPTH        8

typedef enum { FLASH_OP_READ, FLASH_OP_WRITE, FLASH_OP_ERASE } flash_op_t;

typedef struct {
    flash_op_t   op;
    uint32_t     addr;
    void        *buf;
    uint32_t     size;
    TaskHandle_t caller;
} flash_req_t;

static volatile QueueHandle_t s_flash_queue;
static volatile int           s_flash_init; /* 0=uninit 1=initing 2=ready */

static void __flash_do(flash_op_t op, uint32_t addr, void *buf, uint32_t size,
                       OPERATE_RET *out)
{
    const esp_partition_t *p = GET_TUYA_DATA_PARTITION();
    if (!p) { *out = OPRT_COM_ERROR; return; }
    switch (op) {
    case FLASH_OP_READ:
        *out = esp_partition_read(p, addr, buf, size) == ESP_OK ? OPRT_OK : OPRT_COM_ERROR;
        break;
    case FLASH_OP_WRITE:
        *out = esp_partition_write(p, addr, buf, size) == ESP_OK ? OPRT_OK : OPRT_COM_ERROR;
        break;
    case FLASH_OP_ERASE:
        *out = esp_partition_erase_range(p, addr, size) == ESP_OK ? OPRT_OK : OPRT_COM_ERROR;
        break;
    }
}

static void __flash_worker(void *arg)
{
    flash_req_t req;
    OPERATE_RET ret;
    for (;;) {
        if (xQueueReceive(s_flash_queue, &req, portMAX_DELAY) != pdTRUE) continue;
        __flash_do(req.op, req.addr, req.buf, req.size, &ret);
        xTaskNotify(req.caller, (uint32_t)ret, eSetValueWithOverwrite);
    }
}

static void __ensure_worker(void)
{
    int expected = 0;
    if (__atomic_compare_exchange_n(&s_flash_init, &expected, 1, false,
                                    __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST)) {
        s_flash_queue = xQueueCreate(FLASH_QUEUE_DEPTH, sizeof(flash_req_t));
        xTaskCreateWithCaps(__flash_worker, "flash_wkr",
                            FLASH_WORKER_STACK_SIZE, NULL,
                            FLASH_WORKER_PRIORITY, NULL,
                            MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT);
        __atomic_store_n(&s_flash_init, 2, __ATOMIC_SEQ_CST);
    } else {
        while (__atomic_load_n(&s_flash_init, __ATOMIC_SEQ_CST) != 2) vTaskDelay(1);
    }
}

static bool __stack_in_psram(void)
{
#if defined(CONFIG_SPIRAM)
    void *sp;
    __asm__ volatile("mov %0, a1" : "=r"(sp));
    return ((uintptr_t)sp >= SOC_EXTRAM_DATA_LOW && (uintptr_t)sp < SOC_EXTRAM_DATA_HIGH);
#else
    return false;
#endif
}

static OPERATE_RET __flash_exec(flash_op_t op, uint32_t addr, void *buf, uint32_t size)
{
    if (!__stack_in_psram()) {
        OPERATE_RET ret;
        __flash_do(op, addr, buf, size, &ret);
        return ret;
    }
    __ensure_worker();
    flash_req_t req = {
        .op     = op,
        .addr   = addr,
        .buf    = buf,
        .size   = size,
        .caller = xTaskGetCurrentTaskHandle(),
    };
    xTaskNotifyStateClear(NULL);
    xQueueSend(s_flash_queue, &req, portMAX_DELAY);
    uint32_t result = (uint32_t)OPRT_COM_ERROR;
    xTaskNotifyWait(0, UINT32_MAX, &result, portMAX_DELAY);
    return (OPERATE_RET)(int)result;
}
// --- END: user defines and implements ---

/**
* @brief read flash
*
* @param[in] addr: flash address
* @param[out] dst: pointer of buffer
* @param[in] size: size of buffer
*
* @note This API is used for reading flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_read(uint32_t addr, uint8_t *dst, uint32_t size)
{
    // --- BEGIN: user implements ---
    if (NULL == dst) {
        return OPRT_INVALID_PARM;
    }
    return __flash_exec(FLASH_OP_READ, addr, dst, size);
    // --- END: user implements ---
}

/**
* @brief write flash
*
* @param[in] addr: flash address
* @param[in] src: pointer of buffer
* @param[in] size: size of buffer
*
* @note This API is used for writing flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_write(uint32_t addr, const uint8_t *src, uint32_t size)
{
    // --- BEGIN: user implements ---
    if (NULL == src) {
        return OPRT_INVALID_PARM;
    }
    return __flash_exec(FLASH_OP_WRITE, addr, (void *)src, size);
    // --- END: user implements ---
}

/**
* @brief erase flash
*
* @param[in] addr: flash address
* @param[in] size: size of flash block
*
* @note This API is used for erasing flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_erase(uint32_t addr, uint32_t size)
{
    // --- BEGIN: user implements ---
    return __flash_exec(FLASH_OP_ERASE, addr, NULL, size);
    // --- END: user implements ---
}

/**
* @brief lock flash
*
* @param[in] addr: lock begin addr
* @param[in] size: lock area size
*
* @note This API is used for lock flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_lock(uint32_t addr, uint32_t size)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
* @brief unlock flash
*
* @param[in] addr: unlock begin addr
* @param[in] size: unlock area size
*
* @note This API is used for unlock flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_unlock(uint32_t addr, uint32_t size)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
* @brief get flash information
*
* @param[out] info: the description of the flash
*
* @note This API is used to get description of storage.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_get_one_type_info(TUYA_FLASH_TYPE_E type, TUYA_FLASH_BASE_INFO_T* info)
{
    // --- BEGIN: user implements ---
    if ((type > TUYA_FLASH_TYPE_MAX) || (info == NULL)) {
        return OPRT_INVALID_PARM;
    }
    switch (type) {
        case TUYA_FLASH_TYPE_UF:
            info->partition_num = 1;
            info->partition[0].block_size =  PARTITION_SIZE;
            info->partition[0].start_addr = UF_PARTITION_START;
            info->partition[0].size = UF_PARTITION_SIZE;
            break;
       case TUYA_FLASH_TYPE_KV_DATA:
            info->partition_num = 1;
            info->partition[0].block_size = FLH_BLOCK_SZ;
            info->partition[0].start_addr = SIMPLE_FLASH_START;
            info->partition[0].size = SIMPLE_FLASH_SIZE;
            break;
       case TUYA_FLASH_TYPE_KV_KEY:
            info->partition_num = 1;
            info->partition[0].block_size = FLH_BLOCK_SZ;
            info->partition[0].start_addr = SIMPLE_FLASH_KEY_ADDR;
            info->partition[0].size = FLH_BLOCK_SZ;
            break;
#if defined(KV_PROTECTED_ENABLE) && (KV_PROTECTED_ENABLE==1)
        case TUYA_FLASH_TYPE_KV_PROTECT:
            info->partition_num = 1;
            info->partition[0].block_size = FLH_BLOCK_SZ;
            info->partition[0].start_addr = SIMPLE_FLASH_KV_PROTECTED_START;
            info->partition[0].size = SIMPLE_FLASH_KV_PROTECTED_SIZE;
            break;
#endif
        default:
            return OPRT_INVALID_PARM;
            break;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief tuya_iot_license_read
*
* @param[in] license: iot license struct pointer
*
* @note This API is used for read license .
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
int tuya_iot_license_read(tuya_iot_license_t *license)
{
    return OPRT_NOT_SUPPORTED;
}
