/**
 * @file tkl_flash.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */

// --- BEGIN: user defines and implements ---
#include "tkl_flash.h"
#include "tuya_error_code.h"
#include "esp_partition.h"

/* TODO: need to consider whether to use locks at the TKL layer*/
#define PARTITION_SIZE         (1 << 12) /* 4KB */
#define FLH_BLOCK_SZ            PARTITION_SIZE

//key
#define SIMPLE_FLASH_KEY_ADDR 0x0 /* offset of tuya data partition */

//KV
#define SIMPLE_FLASH_START (SIMPLE_FLASH_KEY_ADDR + PARTITION_SIZE)
#define SIMPLE_FLASH_SIZE 0x8000 // 32K

//UF
#define UF_PARTITION_NUM     1
#define UF_PARTITION_START  (SIMPLE_FLASH_START + SIMPLE_FLASH_SIZE)
#define UF_PARTITION_SIZE   0x18000 // 96K

#if defined(KV_PROTECTED_ENABLE) && (KV_PROTECTED_ENABLE==1)
#define SIMPLE_FLASH_KV_PROTECTED_START (UF_PARTITION_START + UF_PARTITION_SIZE)
#define SIMPLE_FLASH_KV_PROTECTED_SIZE 0x1000 //4K
#endif

#define GET_TUYA_DATA_PARTITION() esp_partition_find_first(ESP_PARTITION_TYPE_DATA, ESP_PARTITION_SUBTYPE_ANY, "tuya")

typedef struct {
    char *uuid;
    char *authkey;
} tuya_iot_license_t;

#if CONFIG_IDF_TARGET_ESP32S3
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"

typedef enum {
    FLASH_OP_READ = 0,
    FLASH_OP_WRITE,
    FLASH_OP_ERASE,
} FLASH_OP_TYPE_E;

typedef struct {
    FLASH_OP_TYPE_E op;
    uint32_t addr;
    union {
        const uint8_t *src;
        uint8_t *dst;
    };
    uint32_t size;
    TaskHandle_t caller;
    OPERATE_RET result;
} FLASH_REQ_T;

static QueueHandle_t s_flash_queue = NULL;

static OPERATE_RET __flash_dispatch(FLASH_REQ_T *req)
{
    req->caller = xTaskGetCurrentTaskHandle();
    FLASH_REQ_T *preq = req;
    xQueueSend(s_flash_queue, &preq, portMAX_DELAY);
    ulTaskNotifyTake(pdTRUE, portMAX_DELAY);
    return req->result;
}

void tkl_flash_agent_init(void)
{
    s_flash_queue = xQueueCreate(8, sizeof(FLASH_REQ_T *));
}

void tkl_flash_agent_process(void)
{
    FLASH_REQ_T *req = NULL;

    if (xQueueReceive(s_flash_queue, &req, portMAX_DELAY) != pdTRUE || req == NULL) {
        return;
    }

    const esp_partition_t *partition = GET_TUYA_DATA_PARTITION();
    if (partition == NULL) {
        req->result = OPRT_COM_ERROR;
        xTaskNotifyGive(req->caller);
        return;
    }

    switch (req->op) {
        case FLASH_OP_READ:
            req->result = (esp_partition_read(partition, req->addr, req->dst, req->size) == ESP_OK)
                          ? OPRT_OK : OPRT_COM_ERROR;
            break;
        case FLASH_OP_WRITE:
            req->result = (esp_partition_write(partition, req->addr, req->src, req->size) == ESP_OK)
                          ? OPRT_OK : OPRT_COM_ERROR;
            break;
        case FLASH_OP_ERASE:
            req->result = (esp_partition_erase_range(partition, req->addr, req->size) == ESP_OK)
                          ? OPRT_OK : OPRT_COM_ERROR;
            break;
        default:
            req->result = OPRT_INVALID_PARM;
            break;
    }

    xTaskNotifyGive(req->caller);
}
#endif
// --- END: user defines and implements ---

/**
* @brief read flash
*
* @param[in] addr: flash address
* @param[out] dst: pointer of buffer
* @param[in] size: size of buffer
*
* @note This API is used for reading flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_read(uint32_t addr, uint8_t *dst, uint32_t size)
{
    // --- BEGIN: user implements ---
    if (NULL == dst) {
        return OPRT_INVALID_PARM;
    }

#if CONFIG_IDF_TARGET_ESP32S3
    if (s_flash_queue != NULL) {
        FLASH_REQ_T req = { .op = FLASH_OP_READ, .addr = addr, .dst = dst, .size = size };
        return __flash_dispatch(&req);
    }
#endif

    const esp_partition_t *partition = GET_TUYA_DATA_PARTITION();
    if (NULL == partition) {
        return OPRT_COM_ERROR;
    }

    if (ESP_OK != esp_partition_read(partition, addr, dst, size)) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief write flash
*
* @param[in] addr: flash address
* @param[in] src: pointer of buffer
* @param[in] size: size of buffer
*
* @note This API is used for writing flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_write(uint32_t addr, const uint8_t *src, uint32_t size)
{
    // --- BEGIN: user implements ---
    if (NULL == src) {
        return OPRT_INVALID_PARM;
    }

#if CONFIG_IDF_TARGET_ESP32S3
    if (s_flash_queue != NULL) {
        FLASH_REQ_T req = { .op = FLASH_OP_WRITE, .addr = addr, .src = src, .size = size };
        return __flash_dispatch(&req);
    }
#endif

    const esp_partition_t *partition = GET_TUYA_DATA_PARTITION();
    if (NULL == partition) {
        return OPRT_COM_ERROR;
    }

    if (ESP_OK != esp_partition_write(partition, addr, src, size)) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief erase flash
*
* @param[in] addr: flash address
* @param[in] size: size of flash block
*
* @note This API is used for erasing flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_erase(uint32_t addr, uint32_t size)
{
    // --- BEGIN: user implements ---
#if CONFIG_IDF_TARGET_ESP32S3
    if (s_flash_queue != NULL) {
        FLASH_REQ_T req = { .op = FLASH_OP_ERASE, .addr = addr, .size = size };
        return __flash_dispatch(&req);
    }
#endif

    const esp_partition_t *partition = GET_TUYA_DATA_PARTITION();
    if (NULL == partition) {
        return OPRT_COM_ERROR;
    }

    if (ESP_OK != esp_partition_erase_range(partition, addr, size)) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief lock flash
*
* @param[in] addr: lock begin addr
* @param[in] size: lock area size
*
* @note This API is used for lock flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_lock(uint32_t addr, uint32_t size)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
* @brief unlock flash
*
* @param[in] addr: unlock begin addr
* @param[in] size: unlock area size
*
* @note This API is used for unlock flash.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_unlock(uint32_t addr, uint32_t size)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
* @brief get flash information
*
* @param[out] info: the description of the flash
*
* @note This API is used to get description of storage.
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
OPERATE_RET tkl_flash_get_one_type_info(TUYA_FLASH_TYPE_E type, TUYA_FLASH_BASE_INFO_T* info)
{
    // --- BEGIN: user implements ---
    if ((type > TUYA_FLASH_TYPE_MAX) || (info == NULL)) {
        return OPRT_INVALID_PARM;
    }
    switch (type) {
        case TUYA_FLASH_TYPE_UF:
            info->partition_num = 1;
            info->partition[0].block_size =  PARTITION_SIZE;
            info->partition[0].start_addr = UF_PARTITION_START;
            info->partition[0].size = UF_PARTITION_SIZE;
            break;
       case TUYA_FLASH_TYPE_KV_DATA:
            info->partition_num = 1;
            info->partition[0].block_size = FLH_BLOCK_SZ;
            info->partition[0].start_addr = SIMPLE_FLASH_START;
            info->partition[0].size = SIMPLE_FLASH_SIZE;
            break;
       case TUYA_FLASH_TYPE_KV_KEY:
            info->partition_num = 1;
            info->partition[0].block_size = FLH_BLOCK_SZ;
            info->partition[0].start_addr = SIMPLE_FLASH_KEY_ADDR;
            info->partition[0].size = FLH_BLOCK_SZ;
            break;
#if defined(KV_PROTECTED_ENABLE) && (KV_PROTECTED_ENABLE==1)
        case TUYA_FLASH_TYPE_KV_PROTECT:
            info->partition_num = 1;
            info->partition[0].block_size = FLH_BLOCK_SZ;
            info->partition[0].start_addr = SIMPLE_FLASH_KV_PROTECTED_START;
            info->partition[0].size = SIMPLE_FLASH_KV_PROTECTED_SIZE;
            break;
#endif
        default:
            return OPRT_INVALID_PARM;
            break;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
* @brief tuya_iot_license_read
*
* @param[in] license: iot license struct pointer
*
* @note This API is used for read license .
*
* @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
*/
int tuya_iot_license_read(tuya_iot_license_t *license)
{
    return OPRT_NOT_SUPPORTED;
}