/**
 * @file tkl_bt.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 * 
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 * 
 */
#include "freertos/FreeRTOS.h"
#include "esp_err.h"
#include "esp_log.h"
#ifndef CONFIG_IDF_TARGET_ESP32P4
#include "esp_bt.h"
#endif

#include "tuya_error_code.h"
#include "tuya_cloud_types.h"
#include "tkl_memory.h"
#include "tkl_system.h"
#include "tkl_output.h"
#include "tkl_bluetooth.h"
#include "tkl_hci.h"

#define DBG_TAG "TKL_BLE"
#define BLE_HCI_CMD_MSG_TYPE        0x01 	/* command message type */
#define BLE_HCI_ACL_MSG_TYPE        0x02    /* ACL data message type */
#define BLE_HCI_SYNC_MSG_TYPE       0x03    /* Synchronous data message type */
#define BLE_HCI_EVT_MSG_TYPE        0x04    /* event message type */

#define BLE_HCI_CMD_MSG_TYPE_LEN 1
#define BLE_HCI_ACL_MSG_TYPE_LEN 1

#ifndef CONFIG_IDF_TARGET_ESP32P4

static TKL_HCI_FUNC_CB tuya_ble_hci_rx_cmd_hs_cb;
static TKL_HCI_FUNC_CB tuya_ble_hci_rx_acl_hs_cb;
#define TRACE_PACKET_DEBUG(t, buf, len) ESP_LOG_BUFFER_HEXDUMP((t), (buf), (len), ESP_LOG_INFO)

static void controller_rcv_pkt_ready(void)
{
	//ESP_LOGI(DBG_TAG, "%s: controller rcv pkt ready", __func__);
}

int tuya_ble_hci_ll_tx(uint8_t *data, uint16_t len)
{
	uint8_t type;

	if (NULL == data || 0 == len) {
		ESP_LOGE(DBG_TAG, "%s: input invalid params", __func__);
		return -1;
	}

	type = data[0];
	//TRACE_PACKET_DEBUG("tuya_ble_hci_ll_tx", data, len);

	switch (type) {
	case BLE_HCI_EVT_MSG_TYPE:
		if (tuya_ble_hci_rx_cmd_hs_cb) {
			tuya_ble_hci_rx_cmd_hs_cb(data + BLE_HCI_CMD_MSG_TYPE_LEN, len - BLE_HCI_CMD_MSG_TYPE_LEN);
		}
		break;
	case BLE_HCI_ACL_MSG_TYPE:
		if (tuya_ble_hci_rx_acl_hs_cb) {
			tuya_ble_hci_rx_acl_hs_cb(data + BLE_HCI_ACL_MSG_TYPE_LEN, len - BLE_HCI_ACL_MSG_TYPE_LEN);
		}
		break;
	default:
		ESP_LOGI(DBG_TAG, "%s: unsupport message type %d", __func__, type);
		break;			
 	} /* end switch (type) { */

	return 0;
}

/**
 * Sends an HCI command from the host to the controller.
 *
 * @param cmd                   The HCI command to send.  This buffer must be
 *                                  allocated via tuya_ble_hci_buf_alloc().
 *
 * @retval 0                    success
 * @retval Other                fail
 *                              A BLE_ERR_[...] error code on failure.
 */
OPERATE_RET tkl_hci_cmd_packet_send(const uint8_t *p_buf, uint16_t buf_len)
{
	uint8_t *cmd_buf;
	uint16_t cmd_buf_len;

	if (NULL == p_buf || 0 == buf_len) {
		ESP_LOGE(DBG_TAG, "%s: input invalid params", __func__);
		return OPRT_INVALID_PARM;
	}

	if (!esp_vhci_host_check_send_available()) {
		ESP_LOGE(DBG_TAG, "%s: hci send is not available", __func__);
		return OPRT_COM_ERROR;
	}

	cmd_buf_len = buf_len + BLE_HCI_CMD_MSG_TYPE_LEN;
	cmd_buf = tkl_system_malloc(cmd_buf_len);
	if (NULL == cmd_buf) {
		return OPRT_MALLOC_FAILED;
	}

	*cmd_buf = BLE_HCI_CMD_MSG_TYPE;
	memcpy(cmd_buf + BLE_HCI_CMD_MSG_TYPE_LEN, p_buf, buf_len);
	//TRACE_PACKET_DEBUG("tkl_hci_cmd_packet_send", cmd_buf, cmd_buf_len);

	esp_vhci_host_send_packet(cmd_buf, cmd_buf_len);
	tkl_system_free(cmd_buf);
	cmd_buf = NULL;
	return OPRT_OK;
}

/**
 * Sends ACL data from host to controller.
 *
 * @param om                    The ACL data packet to send.
 *
 * @retval 0                    success
 * @retval Other                fail
 *                              A BLE_ERR_[...] error code on failure.
 */
OPERATE_RET tkl_hci_acl_packet_send(const uint8_t *p_buf, uint16_t buf_len)
{
	uint8_t *acl_buf;
	uint16_t acl_buf_len;

	if (NULL == p_buf || 0 == buf_len) {
		ESP_LOGE(DBG_TAG, "%s: input invalid params", __func__);
		return OPRT_INVALID_PARM;
	}

	if (!esp_vhci_host_check_send_available()) {
		ESP_LOGE(DBG_TAG, "%s: hci send is not available", __func__);
		return OPRT_COM_ERROR;
	}

	acl_buf_len = buf_len + BLE_HCI_ACL_MSG_TYPE_LEN;
	acl_buf = tkl_system_malloc(acl_buf_len);
	if (NULL == acl_buf) {
		return OPRT_MALLOC_FAILED;
	}

	*acl_buf = BLE_HCI_ACL_MSG_TYPE;
	memcpy(acl_buf + BLE_HCI_ACL_MSG_TYPE_LEN, p_buf, buf_len);

	//TRACE_PACKET_DEBUG("tkl_hci_acl_packet_send", acl_buf, acl_buf_len);
	esp_vhci_host_send_packet(acl_buf, acl_buf_len);
	tkl_system_free(acl_buf);
	acl_buf = NULL;
	return OPRT_OK;
}

OPERATE_RET tkl_hci_callback_register(const TKL_HCI_FUNC_CB hci_evt_cb, const TKL_HCI_FUNC_CB acl_pkt_cb)
{
    tuya_ble_hci_rx_cmd_hs_cb = hci_evt_cb;
    tuya_ble_hci_rx_acl_hs_cb = acl_pkt_cb;
	return OPRT_OK;
}

static esp_vhci_host_callback_t vhci_host_cb = {
    .notify_host_send_available = controller_rcv_pkt_ready,
    .notify_host_recv = tuya_ble_hci_ll_tx
};

/**
 * Resets the HCI module to a clean state.  Frees all buffers and reinitializes
 * the underlying transport.
 *
 * @retval 0                    success
 * @retval Other                fail
 *                              A BLE_ERR_[...] error code on failure.
 */
OPERATE_RET tkl_hci_reset(void)
{
	//uint16_t size; 
	//uint8_t cmd_buf[128] = { 0 };

	if (!esp_vhci_host_check_send_available()) {
		ESP_LOGE(DBG_TAG, "%s: hci send is not available", __func__);
		return OPRT_COM_ERROR;
	}

	//size = make_cmd_reset(cmd_buf);
	//esp_vhci_host_send_packet(cmd_buf, size);
	return OPRT_OK;
}

/**
 * Init the HCI module
 *
 * @retval 0                    success
 * @retval Other                fail
 *                              A BLE_ERR_[...] error code on failure.
 */
OPERATE_RET tkl_hci_init(void)
{
	esp_err_t ret;
	esp_bt_controller_config_t bt_cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();

	ret = esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT);
	if (ESP_OK != ret) {
		ESP_LOGE(DBG_TAG, "%s: call esp_bt_controller_mem_release failed(ret=%d)", __func__, ret);
		return OPRT_COM_ERROR;
	}

	ret = esp_bt_controller_init(&bt_cfg);
	if (ESP_OK != ret) {
		ESP_LOGE(DBG_TAG, "%s: call esp_bt_controller_init failed(ret=%d)", __func__, ret);
		return OPRT_COM_ERROR;
	}

	ret = esp_bt_controller_enable(ESP_BT_MODE_BLE);
	if (ESP_OK != ret) {
		ESP_LOGE(DBG_TAG, "%s: call esp_bt_controller_enable failed(ret=%d)", __func__, ret);
		return OPRT_COM_ERROR;
	}

	esp_vhci_host_register_callback(&vhci_host_cb);
	return OPRT_OK;
}

/* Deinit the controller and hci interface*/
/* Host Use */
OPERATE_RET tkl_hci_deinit(void)
{
	esp_err_t ret;
    
	ret = esp_bt_controller_disable();
	if (ESP_OK != ret) {
		ESP_LOGE(DBG_TAG, "%s: call esp_bt_controller_disable failed", __func__);
		return OPRT_COM_ERROR;
	}

    ret = esp_bt_controller_deinit();
	if (ESP_OK != ret) {
		ESP_LOGE(DBG_TAG, "%s: call esp_bt_controller_deinit failed", __func__);
		return OPRT_COM_ERROR;
	}

    return OPRT_OK;
}

#else /* CONFIG_IDF_TARGET_ESP32P4 */

/* ---------------------------------------------------------------------------
 * ESP32-P4 + C6 (via ESP-Hosted) BT/BLE HCI bridge
 *
 * P4 has no local BT controller. The BT controller lives on the C6
 * coprocessor and is reached through ESP-Hosted's SDIO transport using
 * the HCI-over-Hosted (ESP_HCI_IF) channel.
 *
 * Tuya's NimBLE host (in src/tal_bluetooth/nimble) talks HCI through the
 * tkl_hci_* API:
 *   tkl_hci_cmd_packet_send / tkl_hci_acl_packet_send  -> host to controller
 *   callbacks registered by tkl_hci_callback_register  <- controller to host
 *
 * Payloads on the wire include an H4 type byte (CMD/ACL/EVT) as the first
 * byte; tkl_hci_* APIs use raw HCI without the type byte, so we add/strip
 * it here.
 *
 * The ESP-Hosted SDIO Rx path calls a global hci_rx_handler() when a packet
 * of if_type ESP_HCI_IF arrives. We provide a strong override of that
 * symbol (the upstream stub is marked WEAK).
 * --------------------------------------------------------------------------- */

#include <stdlib.h>
#include <string.h>

/* Forward declarations of ESP-Hosted internals (kept in sync with
 * managed_components/espressif__esp_hosted/host/utils/common.h and
 * host/drivers/transport/transport_drv.h). Using forward declarations
 * avoids polluting tkl_bt.c with the entire ESP-Hosted private include
 * tree. */
typedef struct {
    union {
        void *priv_buffer_handle;
    };
    uint8_t  if_type;
    uint8_t  if_num;
    uint8_t *payload;
    uint8_t  flag;
    uint16_t payload_len;
    uint16_t seq_num;
    uint8_t  payload_zcopy;
    void (*free_buf_handle)(void *buf_handle);
} interface_buffer_handle_t;

/* From esp_hosted_interface.h:
 *   ESP_INVALID_IF=0, ESP_STA_IF=1, ESP_AP_IF=2, ESP_SERIAL_IF=3,
 *   ESP_HCI_IF=4,     ESP_PRIV_IF=5, ESP_TEST_IF=6, ESP_ETH_IF=7.
 * (We intentionally avoid pulling esp_hosted_interface.h into the adapter,
 * but the value must match exactly or the SDIO Tx path won't treat the
 * frame as HCI and won't move the H4 type byte into hci_pkt_type.) */
#define TKL_ESP_HCI_IF              4
#define TKL_H_BUFF_NO_ZEROCOPY      0

extern int esp_hosted_tx(uint8_t iface_type, uint8_t iface_num,
                         uint8_t *buffer, uint16_t len, uint8_t buff_zerocopy,
                         void (*free_buf_fun)(void *ptr));

/* H4 packet types */
#define TKL_HCI_H4_CMD              0x01
#define TKL_HCI_H4_ACL              0x02
#define TKL_HCI_H4_EVT              0x04

/* Tuya HCI Rx callbacks registered by tkl_hci_callback_register(). */
static TKL_HCI_FUNC_CB s_tuya_evt_cb;
static TKL_HCI_FUNC_CB s_tuya_acl_cb;

/* Tx helpers ----------------------------------------------------------- */

static void tkl_hci_free_tx_buf(void *ptr)
{
    if (ptr) {
        free(ptr);
    }
}

static OPERATE_RET tkl_hci_tx_with_h4(uint8_t h4_type, const uint8_t *p_buf, uint16_t buf_len)
{
    if (NULL == p_buf || 0 == buf_len) {
        ESP_LOGE(DBG_TAG, "%s: invalid input", __func__);
        return OPRT_INVALID_PARM;
    }

    uint16_t total_len = (uint16_t)(buf_len + 1);
    uint8_t *data = malloc(total_len);
    if (NULL == data) {
        ESP_LOGE(DBG_TAG, "%s: alloc %u failed", __func__, (unsigned)total_len);
        return OPRT_MALLOC_FAILED;
    }
    data[0] = h4_type;
    memcpy(&data[1], p_buf, buf_len);

    int ret = esp_hosted_tx(TKL_ESP_HCI_IF, 0, data, total_len,
                            TKL_H_BUFF_NO_ZEROCOPY, tkl_hci_free_tx_buf);
    if (ret != 0) {
        ESP_LOGW(DBG_TAG, "%s: esp_hosted_tx failed (%d)", __func__, ret);
        /* esp_hosted_tx is responsible for invoking free_buf_fun on success;
         * on failure (queue full etc.) free here to avoid leaks. */
        free(data);
        return OPRT_COM_ERROR;
    }
    return OPRT_OK;
}

OPERATE_RET tkl_hci_cmd_packet_send(const uint8_t *p_buf, uint16_t buf_len)
{
    return tkl_hci_tx_with_h4(TKL_HCI_H4_CMD, p_buf, buf_len);
}

OPERATE_RET tkl_hci_acl_packet_send(const uint8_t *p_buf, uint16_t buf_len)
{
    return tkl_hci_tx_with_h4(TKL_HCI_H4_ACL, p_buf, buf_len);
}

OPERATE_RET tkl_hci_callback_register(const TKL_HCI_FUNC_CB hci_evt_cb, const TKL_HCI_FUNC_CB acl_pkt_cb)
{
    s_tuya_evt_cb = hci_evt_cb;
    s_tuya_acl_cb = acl_pkt_cb;
    return OPRT_OK;
}

OPERATE_RET tkl_hci_reset(void)
{
    /* The C6 controller is reset by ESP-Hosted during its bring-up. Nothing
     * to do here from the host adapter; NimBLE will issue HCI_Reset later. */
    return OPRT_OK;
}

OPERATE_RET tkl_hci_init(void)
{
    /* ESP-Hosted brings up the SDIO link and the C6 controller before this
     * point. NimBLE drives the HCI exchange through tkl_hci_cmd_packet_send;
     * no extra controller init is needed here. */
    return OPRT_OK;
}

OPERATE_RET tkl_hci_deinit(void)
{
    s_tuya_evt_cb = NULL;
    s_tuya_acl_cb = NULL;
    return OPRT_OK;
}

/* Rx path: wraps the esp_hosted stub via --wrap linker flag. Called by
 * ESP-Hosted transport when an ESP_HCI_IF packet arrives from the C6. */
int __wrap_hci_rx_handler(interface_buffer_handle_t *buf_handle)
{
    if (NULL == buf_handle || NULL == buf_handle->payload || buf_handle->payload_len < 1) {
        return 0;
    }

    uint8_t  h4_type = buf_handle->payload[0];
    uint8_t *data    = buf_handle->payload + 1;
    uint16_t len     = (uint16_t)(buf_handle->payload_len - 1);

    switch (h4_type) {
    case TKL_HCI_H4_EVT:
        if (s_tuya_evt_cb) {
            s_tuya_evt_cb(data, len);
        }
        break;
    case TKL_HCI_H4_ACL:
        if (s_tuya_acl_cb) {
            s_tuya_acl_cb(data, len);
        }
        break;
    default:
        ESP_LOGW(DBG_TAG, "hci_rx_handler: unsupported H4 type 0x%02x", h4_type);
        break;
    }
    return 0;
}

#endif /* CONFIG_IDF_TARGET_ESP32P4 */
